In [1]:
import requests

In [2]:
population_url = "https://raw.githubusercontent.com/NaftalyMunene/KENYAN_POPULATION/refs/heads/main/POPULATION_DATA.json"

In [3]:
population_data = requests.get(population_url)

In [5]:
type(population_data)

requests.models.Response

In [6]:
population_data_json = population_data.json()

In [8]:
type(population_data_json)

list

In [9]:
import pandas

In [11]:
kenya_population_data = pandas.DataFrame(population_data_json)

In [12]:
kenya_population_data.to_csv("kenya_population_data.csv")

In [14]:
kenya_population_data

    county_name  population  area_sq_km  population_density major_city
0        Nakuru     2398162       19512          122.907032    Nairobi
1       Nairobi     9681385       14725          657.479457     Kisumu
2        Kisumu     8692283        2002         4341.799700     Kisumu
3        Kisumu     8697417        5084         1710.742919     Kisumu
4        Kisumu     2817773        4567          616.985549     Nakuru
..          ...         ...         ...                 ...        ...
495      Kisumu     7995913       23225          344.280431    Mombasa
496     Eldoret     5013176       36919          135.788510     Kisumu
497      Kisumu     2760405       12444          221.826181    Mombasa
498      Nakuru     9395373       27750          338.572000     Nakuru
499     Eldoret     9094196       29737          305.820897    Eldoret

[500 rows x 5 columns]

In [ ]:
####products fromdummyjson

In [15]:
products_url  = "https://dummyjson.com/products"

In [16]:
products_data = requests.get(products_url)

In [17]:
products_data_json = products_data.json()

In [18]:
type(products_data_json)

dict

In [19]:
products_data_final = pandas.DataFrame(products_data_json)

In [20]:
products_data_final.to_csv("products_data.csv")

In [21]:
products_data_final

                                             products  total  skip  limit
0   {'id': 1, 'title': 'Essence Mascara Lash Princ...    194     0     30
1   {'id': 2, 'title': 'Eyeshadow Palette with Mir...    194     0     30
2   {'id': 3, 'title': 'Powder Canister', 'descrip...    194     0     30
3   {'id': 4, 'title': 'Red Lipstick', 'descriptio...    194     0     30
4   {'id': 5, 'title': 'Red Nail Polish', 'descrip...    194     0     30
5   {'id': 6, 'title': 'Calvin Klein CK One', 'des...    194     0     30
6   {'id': 7, 'title': 'Chanel Coco Noir Eau De', ...    194     0     30
7   {'id': 8, 'title': 'Dior J'adore', 'descriptio...    194     0     30
8   {'id': 9, 'title': 'Dolce Shine Eau de', 'desc...    194     0     30
9   {'id': 10, 'title': 'Gucci Bloom Eau de', 'des...    194     0     30
10  {'id': 11, 'title': 'Annibale Colombo Bed', 'd...    194     0     30
11  {'id': 12, 'title': 'Annibale Colombo Sofa', '...    194     0     30
12  {'id': 13, 'title': 'Bedside Table African Che...    194     0     30
13  {'id': 14, 'title': 'Knoll Saarinen Executive ...    194     0     30
14  {'id': 15, 'title': 'Wooden Bathroom Sink With...    194     0     30
15  {'id': 16, 'title': 'Apple', 'description': 'F...    194     0     30
16  {'id': 17, 'title': 'Beef Steak', 'description...    194     0     30
17  {'id': 18, 'title': 'Cat Food', 'description':...    194     0     30
18  {'id': 19, 'title': 'Chicken Meat', 'descripti...    194     0     30
19  {'id': 20, 'title': 'Cooking Oil', 'descriptio...    194     0     30
20  {'id': 21, 'title': 'Cucumber', 'description':...    194     0     30
21  {'id': 22, 'title': 'Dog Food', 'description':...    194     0     30
22  {'id': 23, 'title': 'Eggs', 'description': 'Fr...    194     0     30
23  {'id': 24, 'title': 'Fish Steak', 'description...    194     0     30
24  {'id': 25, 'title': 'Green Bell Pepper', 'desc...    194     0     30
25  {'id': 26, 'title': 'Green Chili Pepper', 'des...    194     0     30
26  {'id': 27, 'title': 'Honey Jar', 'description'...    194     0     30
27  {'id': 28, 'title': 'Ice Cream', 'description'...    194     0     30
28  {'id': 29, 'title': 'Juice', 'description': 'R...    194     0     30
29  {'id': 30, 'title': 'Kiwi', 'description': 'Nu...    194     0     30

In [ ]:
######

In [22]:
Cart_data_url = "https://dummyjson.com/carts"

In [23]:
cart_data = requests.get(Cart_data_url)

In [24]:
cart_json = cart_data.json()

In [25]:
type(cart_json)

dict

In [26]:
cart_data_final = pandas.DataFrame(cart_json)

In [27]:
cart_data_final.to_csv("cart_data.csv")

In [28]:
cart_data_final

                                                carts  total  skip  limit
0   {'id': 1, 'products': [{'id': 162, 'title': 'B...    208     0     30
1   {'id': 2, 'products': [{'id': 86, 'title': 'Ma...    208     0     30
2   {'id': 3, 'products': [{'id': 24, 'title': 'Fi...    208     0     30
3   {'id': 4, 'products': [{'id': 92, 'title': 'Sp...    208     0     30
4   {'id': 5, 'products': [{'id': 161, 'title': 'S...    208     0     30
5   {'id': 6, 'products': [{'id': 192, 'title': 'R...    208     0     30
6   {'id': 7, 'products': [{'id': 56, 'title': 'El...    208     0     30
7   {'id': 8, 'products': [{'id': 18, 'title': 'Ca...    208     0     30
8   {'id': 9, 'products': [{'id': 1, 'title': 'Ess...    208     0     30
9   {'id': 10, 'products': [{'id': 41, 'title': 'T...    208     0     30
10  {'id': 11, 'products': [{'id': 115, 'title': '...    208     0     30
11  {'id': 12, 'products': [{'id': 117, 'title': '...    208     0     30
12  {'id': 13, 'products': [{'id': 35, 'title': 'P...    208     0     30
13  {'id': 14, 'products': [{'id': 44, 'title': 'F...    208     0     30
14  {'id': 15, 'products': [{'id': 61, 'title': 'H...    208     0     30
15  {'id': 16, 'products': [{'id': 20, 'title': 'C...    208     0     30
16  {'id': 17, 'products': [{'id': 123, 'title': '...    208     0     30
17  {'id': 18, 'products': [{'id': 169, 'title': '...    208     0     30
18  {'id': 19, 'products': [{'id': 22, 'title': 'D...    208     0     30
19  {'id': 20, 'products': [{'id': 123, 'title': '...    208     0     30
20  {'id': 21, 'products': [{'id': 79, 'title': 'A...    208     0     30
21  {'id': 22, 'products': [{'id': 16, 'title': 'A...    208     0     30
22  {'id': 23, 'products': [{'id': 127, 'title': '...    208     0     30
23  {'id': 24, 'products': [{'id': 117, 'title': '...    208     0     30
24  {'id': 25, 'products': [{'id': 32, 'title': 'M...    208     0     30
25  {'id': 26, 'products': [{'id': 122, 'title': '...    208     0     30
26  {'id': 27, 'products': [{'id': 192, 'title': '...    208     0     30
27  {'id': 28, 'products': [{'id': 182, 'title': '...    208     0     30
28  {'id': 29, 'products': [{'id': 174, 'title': '...    208     0     30
29  {'id': 30, 'products': [{'id': 143, 'title': '...    208     0     30